//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication14.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login {
            get {
                return ((string)(this["Login"]));
            }
            set {
                this["Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Opravnenie {
            get {
                return ((string)(this["Opravnenie"]));
            }
            set {
                this["Opravnenie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int CisloZakazky {
            get {
                return ((int)(this["CisloZakazky"]));
            }
            set {
                this["CisloZakazky"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Objednavka {
            get {
                return ((string)(this["Objednavka"]));
            }
            set {
                this["Objednavka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Snimac {
            get {
                return ((string)(this["Snimac"]));
            }
            set {
                this["Snimac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool formulare_otvorenie {
            get {
                return ((bool)(this["formulare_otvorenie"]));
            }
            set {
                this["formulare_otvorenie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5K6HKKB;Initial Catalog=novaDBcsharp;User ID=mukky;Password=m" +
            "arek0")]
        public string novaDBcsharpConnectionString {
            get {
                return ((string)(this["novaDBcsharpConnectionString"]));
            }
            set {
                this["novaDBcsharpConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5K6HKKB;Initial Catalog=ISYS;User ID=mukky;Password=marek0")]
        public string ISYSconnectionstring {
            get {
                return ((string)(this["ISYSconnectionstring"]));
            }
            set {
                this["ISYSconnectionstring"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int rework {
            get {
                return ((int)(this["rework"]));
            }
            set {
                this["rework"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5K6HKKB;Initial Catalog=ISYS;User ID=mukky;Password=marek0")]
        public string ISYSConnectionString1 {
            get {
                return ((string)(this["ISYSConnectionString1"]));
            }
            set {
                this["ISYSConnectionString1"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5K6HKKB;Initial Catalog=novaDBcsharp;User ID=mukky;Password=m" +
            "arek0")]
        public string novaDBcsharpConnectionString1 {
            get {
                return ((string)(this["novaDBcsharpConnectionString1"]));
            }
        }
    }
}
