//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WindowsFormsApplication14
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class novaDBcsharpEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new novaDBcsharpEntities object using the connection string found in the 'novaDBcsharpEntities' section of the application configuration file.
        /// </summary>
        public novaDBcsharpEntities() : base("name=novaDBcsharpEntities", "novaDBcsharpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new novaDBcsharpEntities object.
        /// </summary>
        public novaDBcsharpEntities(string connectionString) : base(connectionString, "novaDBcsharpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new novaDBcsharpEntities object.
        /// </summary>
        public novaDBcsharpEntities(EntityConnection connection) : base(connection, "novaDBcsharpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblObjednavkaDokumenty> tblObjednavkaDokumenty
        {
            get
            {
                if ((_tblObjednavkaDokumenty == null))
                {
                    _tblObjednavkaDokumenty = base.CreateObjectSet<tblObjednavkaDokumenty>("tblObjednavkaDokumenty");
                }
                return _tblObjednavkaDokumenty;
            }
        }
        private ObjectSet<tblObjednavkaDokumenty> _tblObjednavkaDokumenty;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblObjednavkaMaterial> tblObjednavkaMaterial
        {
            get
            {
                if ((_tblObjednavkaMaterial == null))
                {
                    _tblObjednavkaMaterial = base.CreateObjectSet<tblObjednavkaMaterial>("tblObjednavkaMaterial");
                }
                return _tblObjednavkaMaterial;
            }
        }
        private ObjectSet<tblObjednavkaMaterial> _tblObjednavkaMaterial;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblObjednavky> tblObjednavky
        {
            get
            {
                if ((_tblObjednavky == null))
                {
                    _tblObjednavky = base.CreateObjectSet<tblObjednavky>("tblObjednavky");
                }
                return _tblObjednavky;
            }
        }
        private ObjectSet<tblObjednavky> _tblObjednavky;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblObjednavkyStav> tblObjednavkyStav
        {
            get
            {
                if ((_tblObjednavkyStav == null))
                {
                    _tblObjednavkyStav = base.CreateObjectSet<tblObjednavkyStav>("tblObjednavkyStav");
                }
                return _tblObjednavkyStav;
            }
        }
        private ObjectSet<tblObjednavkyStav> _tblObjednavkyStav;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSnimaceZoznam> tblSnimaceZoznam
        {
            get
            {
                if ((_tblSnimaceZoznam == null))
                {
                    _tblSnimaceZoznam = base.CreateObjectSet<tblSnimaceZoznam>("tblSnimaceZoznam");
                }
                return _tblSnimaceZoznam;
            }
        }
        private ObjectSet<tblSnimaceZoznam> _tblSnimaceZoznam;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUzivatelia> tblUzivatelia
        {
            get
            {
                if ((_tblUzivatelia == null))
                {
                    _tblUzivatelia = base.CreateObjectSet<tblUzivatelia>("tblUzivatelia");
                }
                return _tblUzivatelia;
            }
        }
        private ObjectSet<tblUzivatelia> _tblUzivatelia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblZakazky> tblZakazky
        {
            get
            {
                if ((_tblZakazky == null))
                {
                    _tblZakazky = base.CreateObjectSet<tblZakazky>("tblZakazky");
                }
                return _tblZakazky;
            }
        }
        private ObjectSet<tblZakazky> _tblZakazky;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblZakazkyStav> tblZakazkyStav
        {
            get
            {
                if ((_tblZakazkyStav == null))
                {
                    _tblZakazkyStav = base.CreateObjectSet<tblZakazkyStav>("tblZakazkyStav");
                }
                return _tblZakazkyStav;
            }
        }
        private ObjectSet<tblZakazkyStav> _tblZakazkyStav;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblObjednavkaDokumenty EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblObjednavkaDokumenty(tblObjednavkaDokumenty tblObjednavkaDokumenty)
        {
            base.AddObject("tblObjednavkaDokumenty", tblObjednavkaDokumenty);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblObjednavkaMaterial EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblObjednavkaMaterial(tblObjednavkaMaterial tblObjednavkaMaterial)
        {
            base.AddObject("tblObjednavkaMaterial", tblObjednavkaMaterial);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblObjednavky EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblObjednavky(tblObjednavky tblObjednavky)
        {
            base.AddObject("tblObjednavky", tblObjednavky);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblObjednavkyStav EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblObjednavkyStav(tblObjednavkyStav tblObjednavkyStav)
        {
            base.AddObject("tblObjednavkyStav", tblObjednavkyStav);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSnimaceZoznam EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSnimaceZoznam(tblSnimaceZoznam tblSnimaceZoznam)
        {
            base.AddObject("tblSnimaceZoznam", tblSnimaceZoznam);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUzivatelia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUzivatelia(tblUzivatelia tblUzivatelia)
        {
            base.AddObject("tblUzivatelia", tblUzivatelia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblZakazky EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblZakazky(tblZakazky tblZakazky)
        {
            base.AddObject("tblZakazky", tblZakazky);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblZakazkyStav EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblZakazkyStav(tblZakazkyStav tblZakazkyStav)
        {
            base.AddObject("tblZakazkyStav", tblZakazkyStav);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaDBcsharpModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaDBcsharpModel", Name="tblObjednavkaDokumenty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblObjednavkaDokumenty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblObjednavkaDokumenty object.
        /// </summary>
        /// <param name="idObjednavka">Initial value of the IdObjednavka property.</param>
        public static tblObjednavkaDokumenty CreatetblObjednavkaDokumenty(global::System.Int32 idObjednavka)
        {
            tblObjednavkaDokumenty tblObjednavkaDokumenty = new tblObjednavkaDokumenty();
            tblObjednavkaDokumenty.IdObjednavka = idObjednavka;
            return tblObjednavkaDokumenty;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdDokumenty
        {
            get
            {
                return _IdDokumenty;
            }
            set
            {
                OnIdDokumentyChanging(value);
                ReportPropertyChanging("IdDokumenty");
                _IdDokumenty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdDokumenty");
                OnIdDokumentyChanged();
            }
        }
        private global::System.String _IdDokumenty;
        partial void OnIdDokumentyChanging(global::System.String value);
        partial void OnIdDokumentyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdObjednavka
        {
            get
            {
                return _IdObjednavka;
            }
            set
            {
                if (_IdObjednavka != value)
                {
                    OnIdObjednavkaChanging(value);
                    ReportPropertyChanging("IdObjednavka");
                    _IdObjednavka = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdObjednavka");
                    OnIdObjednavkaChanged();
                }
            }
        }
        private global::System.Int32 _IdObjednavka;
        partial void OnIdObjednavkaChanging(global::System.Int32 value);
        partial void OnIdObjednavkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dokument
        {
            get
            {
                return _Dokument;
            }
            set
            {
                OnDokumentChanging(value);
                ReportPropertyChanging("Dokument");
                _Dokument = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dokument");
                OnDokumentChanged();
            }
        }
        private global::System.String _Dokument;
        partial void OnDokumentChanging(global::System.String value);
        partial void OnDokumentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaDBcsharpModel", Name="tblObjednavkaMaterial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblObjednavkaMaterial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblObjednavkaMaterial object.
        /// </summary>
        /// <param name="idMaterial">Initial value of the IdMaterial property.</param>
        /// <param name="idObjednakva">Initial value of the IdObjednakva property.</param>
        public static tblObjednavkaMaterial CreatetblObjednavkaMaterial(global::System.Int32 idMaterial, global::System.Int32 idObjednakva)
        {
            tblObjednavkaMaterial tblObjednavkaMaterial = new tblObjednavkaMaterial();
            tblObjednavkaMaterial.IdMaterial = idMaterial;
            tblObjednavkaMaterial.IdObjednakva = idObjednakva;
            return tblObjednavkaMaterial;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMaterial
        {
            get
            {
                return _IdMaterial;
            }
            set
            {
                OnIdMaterialChanging(value);
                ReportPropertyChanging("IdMaterial");
                _IdMaterial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdMaterial");
                OnIdMaterialChanged();
            }
        }
        private global::System.Int32 _IdMaterial;
        partial void OnIdMaterialChanging(global::System.Int32 value);
        partial void OnIdMaterialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdObjednakva
        {
            get
            {
                return _IdObjednakva;
            }
            set
            {
                if (_IdObjednakva != value)
                {
                    OnIdObjednakvaChanging(value);
                    ReportPropertyChanging("IdObjednakva");
                    _IdObjednakva = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdObjednakva");
                    OnIdObjednakvaChanged();
                }
            }
        }
        private global::System.Int32 _IdObjednakva;
        partial void OnIdObjednakvaChanging(global::System.Int32 value);
        partial void OnIdObjednakvaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SylexPN
        {
            get
            {
                return _SylexPN;
            }
            set
            {
                OnSylexPNChanging(value);
                ReportPropertyChanging("SylexPN");
                _SylexPN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SylexPN");
                OnSylexPNChanged();
            }
        }
        private global::System.String _SylexPN;
        partial void OnSylexPNChanging(global::System.String value);
        partial void OnSylexPNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MnozstvoMaterialu
        {
            get
            {
                return _MnozstvoMaterialu;
            }
            set
            {
                OnMnozstvoMaterialuChanging(value);
                ReportPropertyChanging("MnozstvoMaterialu");
                _MnozstvoMaterialu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MnozstvoMaterialu");
                OnMnozstvoMaterialuChanged();
            }
        }
        private global::System.String _MnozstvoMaterialu;
        partial void OnMnozstvoMaterialuChanging(global::System.String value);
        partial void OnMnozstvoMaterialuChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaDBcsharpModel", Name="tblObjednavky")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblObjednavky : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblObjednavky object.
        /// </summary>
        /// <param name="idObjednavka">Initial value of the IdObjednavka property.</param>
        public static tblObjednavky CreatetblObjednavky(global::System.Int32 idObjednavka)
        {
            tblObjednavky tblObjednavky = new tblObjednavky();
            tblObjednavky.IdObjednavka = idObjednavka;
            return tblObjednavky;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdObjednavka
        {
            get
            {
                return _IdObjednavka;
            }
            set
            {
                if (_IdObjednavka != value)
                {
                    OnIdObjednavkaChanging(value);
                    ReportPropertyChanging("IdObjednavka");
                    _IdObjednavka = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdObjednavka");
                    OnIdObjednavkaChanged();
                }
            }
        }
        private global::System.Int32 _IdObjednavka;
        partial void OnIdObjednavkaChanging(global::System.Int32 value);
        partial void OnIdObjednavkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SylexObjednavka
        {
            get
            {
                return _SylexObjednavka;
            }
            set
            {
                OnSylexObjednavkaChanging(value);
                ReportPropertyChanging("SylexObjednavka");
                _SylexObjednavka = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SylexObjednavka");
                OnSylexObjednavkaChanged();
            }
        }
        private global::System.String _SylexObjednavka;
        partial void OnSylexObjednavkaChanging(global::System.String value);
        partial void OnSylexObjednavkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Zakazka
        {
            get
            {
                return _Zakazka;
            }
            set
            {
                OnZakazkaChanging(value);
                ReportPropertyChanging("Zakazka");
                _Zakazka = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Zakazka");
                OnZakazkaChanged();
            }
        }
        private Nullable<global::System.Int32> _Zakazka;
        partial void OnZakazkaChanging(Nullable<global::System.Int32> value);
        partial void OnZakazkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZakaznickaObjednavka
        {
            get
            {
                return _ZakaznickaObjednavka;
            }
            set
            {
                OnZakaznickaObjednavkaChanging(value);
                ReportPropertyChanging("ZakaznickaObjednavka");
                _ZakaznickaObjednavka = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZakaznickaObjednavka");
                OnZakaznickaObjednavkaChanged();
            }
        }
        private global::System.String _ZakaznickaObjednavka;
        partial void OnZakaznickaObjednavkaChanging(global::System.String value);
        partial void OnZakaznickaObjednavkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StavObjednavka
        {
            get
            {
                return _StavObjednavka;
            }
            set
            {
                OnStavObjednavkaChanging(value);
                ReportPropertyChanging("StavObjednavka");
                _StavObjednavka = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StavObjednavka");
                OnStavObjednavkaChanged();
            }
        }
        private global::System.String _StavObjednavka;
        partial void OnStavObjednavkaChanging(global::System.String value);
        partial void OnStavObjednavkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ObjVytvoril
        {
            get
            {
                return _ObjVytvoril;
            }
            set
            {
                OnObjVytvorilChanging(value);
                ReportPropertyChanging("ObjVytvoril");
                _ObjVytvoril = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ObjVytvoril");
                OnObjVytvorilChanged();
            }
        }
        private global::System.String _ObjVytvoril;
        partial void OnObjVytvorilChanging(global::System.String value);
        partial void OnObjVytvorilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ObjVytvorilDatum
        {
            get
            {
                return _ObjVytvorilDatum;
            }
            set
            {
                OnObjVytvorilDatumChanging(value);
                ReportPropertyChanging("ObjVytvorilDatum");
                _ObjVytvorilDatum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ObjVytvorilDatum");
                OnObjVytvorilDatumChanged();
            }
        }
        private global::System.String _ObjVytvorilDatum;
        partial void OnObjVytvorilDatumChanging(global::System.String value);
        partial void OnObjVytvorilDatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wlNominal_1
        {
            get
            {
                return _wlNominal_1;
            }
            set
            {
                OnwlNominal_1Changing(value);
                ReportPropertyChanging("wlNominal_1");
                _wlNominal_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wlNominal_1");
                OnwlNominal_1Changed();
            }
        }
        private global::System.String _wlNominal_1;
        partial void OnwlNominal_1Changing(global::System.String value);
        partial void OnwlNominal_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wlNominal_2
        {
            get
            {
                return _wlNominal_2;
            }
            set
            {
                OnwlNominal_2Changing(value);
                ReportPropertyChanging("wlNominal_2");
                _wlNominal_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wlNominal_2");
                OnwlNominal_2Changed();
            }
        }
        private global::System.String _wlNominal_2;
        partial void OnwlNominal_2Changing(global::System.String value);
        partial void OnwlNominal_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Snimac
        {
            get
            {
                return _Snimac;
            }
            set
            {
                OnSnimacChanging(value);
                ReportPropertyChanging("Snimac");
                _Snimac = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Snimac");
                OnSnimacChanged();
            }
        }
        private global::System.String _Snimac;
        partial void OnSnimacChanging(global::System.String value);
        partial void OnSnimacChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PnVlakna
        {
            get
            {
                return _PnVlakna;
            }
            set
            {
                OnPnVlaknaChanging(value);
                ReportPropertyChanging("PnVlakna");
                _PnVlakna = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PnVlakna");
                OnPnVlaknaChanged();
            }
        }
        private global::System.String _PnVlakna;
        partial void OnPnVlaknaChanging(global::System.String value);
        partial void OnPnVlaknaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PnVyrobku
        {
            get
            {
                return _PnVyrobku;
            }
            set
            {
                OnPnVyrobkuChanging(value);
                ReportPropertyChanging("PnVyrobku");
                _PnVyrobku = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PnVyrobku");
                OnPnVyrobkuChanged();
            }
        }
        private global::System.String _PnVyrobku;
        partial void OnPnVyrobkuChanging(global::System.String value);
        partial void OnPnVyrobkuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PopisVlakna
        {
            get
            {
                return _PopisVlakna;
            }
            set
            {
                OnPopisVlaknaChanging(value);
                ReportPropertyChanging("PopisVlakna");
                _PopisVlakna = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PopisVlakna");
                OnPopisVlaknaChanged();
            }
        }
        private global::System.String _PopisVlakna;
        partial void OnPopisVlaknaChanging(global::System.String value);
        partial void OnPopisVlaknaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LotVlakna
        {
            get
            {
                return _LotVlakna;
            }
            set
            {
                OnLotVlaknaChanging(value);
                ReportPropertyChanging("LotVlakna");
                _LotVlakna = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LotVlakna");
                OnLotVlaknaChanged();
            }
        }
        private global::System.String _LotVlakna;
        partial void OnLotVlaknaChanging(global::System.String value);
        partial void OnLotVlaknaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PoradoveCisloVlakna
        {
            get
            {
                return _PoradoveCisloVlakna;
            }
            set
            {
                OnPoradoveCisloVlaknaChanging(value);
                ReportPropertyChanging("PoradoveCisloVlakna");
                _PoradoveCisloVlakna = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PoradoveCisloVlakna");
                OnPoradoveCisloVlaknaChanged();
            }
        }
        private global::System.String _PoradoveCisloVlakna;
        partial void OnPoradoveCisloVlaknaChanging(global::System.String value);
        partial void OnPoradoveCisloVlaknaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rework
        {
            get
            {
                return _Rework;
            }
            set
            {
                OnReworkChanging(value);
                ReportPropertyChanging("Rework");
                _Rework = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rework");
                OnReworkChanged();
            }
        }
        private global::System.String _Rework;
        partial void OnReworkChanging(global::System.String value);
        partial void OnReworkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PocetFBG
        {
            get
            {
                return _PocetFBG;
            }
            set
            {
                OnPocetFBGChanging(value);
                ReportPropertyChanging("PocetFBG");
                _PocetFBG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PocetFBG");
                OnPocetFBGChanged();
            }
        }
        private global::System.String _PocetFBG;
        partial void OnPocetFBGChanging(global::System.String value);
        partial void OnPocetFBGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProcessReportVytvoril
        {
            get
            {
                return _ProcessReportVytvoril;
            }
            set
            {
                OnProcessReportVytvorilChanging(value);
                ReportPropertyChanging("ProcessReportVytvoril");
                _ProcessReportVytvoril = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProcessReportVytvoril");
                OnProcessReportVytvorilChanged();
            }
        }
        private global::System.String _ProcessReportVytvoril;
        partial void OnProcessReportVytvorilChanging(global::System.String value);
        partial void OnProcessReportVytvorilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProcessReportVytvorilKedy
        {
            get
            {
                return _ProcessReportVytvorilKedy;
            }
            set
            {
                OnProcessReportVytvorilKedyChanging(value);
                ReportPropertyChanging("ProcessReportVytvorilKedy");
                _ProcessReportVytvorilKedy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProcessReportVytvorilKedy");
                OnProcessReportVytvorilKedyChanged();
            }
        }
        private global::System.String _ProcessReportVytvorilKedy;
        partial void OnProcessReportVytvorilKedyChanging(global::System.String value);
        partial void OnProcessReportVytvorilKedyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProcessReportCesta
        {
            get
            {
                return _ProcessReportCesta;
            }
            set
            {
                OnProcessReportCestaChanging(value);
                ReportPropertyChanging("ProcessReportCesta");
                _ProcessReportCesta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProcessReportCesta");
                OnProcessReportCestaChanged();
            }
        }
        private global::System.String _ProcessReportCesta;
        partial void OnProcessReportCestaChanging(global::System.String value);
        partial void OnProcessReportCestaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KalibracnyListVytvoril
        {
            get
            {
                return _KalibracnyListVytvoril;
            }
            set
            {
                OnKalibracnyListVytvorilChanging(value);
                ReportPropertyChanging("KalibracnyListVytvoril");
                _KalibracnyListVytvoril = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KalibracnyListVytvoril");
                OnKalibracnyListVytvorilChanged();
            }
        }
        private global::System.String _KalibracnyListVytvoril;
        partial void OnKalibracnyListVytvorilChanging(global::System.String value);
        partial void OnKalibracnyListVytvorilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KalibracnyListVytvorilKedy
        {
            get
            {
                return _KalibracnyListVytvorilKedy;
            }
            set
            {
                OnKalibracnyListVytvorilKedyChanging(value);
                ReportPropertyChanging("KalibracnyListVytvorilKedy");
                _KalibracnyListVytvorilKedy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KalibracnyListVytvorilKedy");
                OnKalibracnyListVytvorilKedyChanged();
            }
        }
        private global::System.String _KalibracnyListVytvorilKedy;
        partial void OnKalibracnyListVytvorilKedyChanging(global::System.String value);
        partial void OnKalibracnyListVytvorilKedyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KalibracnyListCesta
        {
            get
            {
                return _KalibracnyListCesta;
            }
            set
            {
                OnKalibracnyListCestaChanging(value);
                ReportPropertyChanging("KalibracnyListCesta");
                _KalibracnyListCesta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KalibracnyListCesta");
                OnKalibracnyListCestaChanged();
            }
        }
        private global::System.String _KalibracnyListCesta;
        partial void OnKalibracnyListCestaChanging(global::System.String value);
        partial void OnKalibracnyListCestaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UkonceneKedy
        {
            get
            {
                return _UkonceneKedy;
            }
            set
            {
                OnUkonceneKedyChanging(value);
                ReportPropertyChanging("UkonceneKedy");
                _UkonceneKedy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UkonceneKedy");
                OnUkonceneKedyChanged();
            }
        }
        private global::System.String _UkonceneKedy;
        partial void OnUkonceneKedyChanging(global::System.String value);
        partial void OnUkonceneKedyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UkonceneKto
        {
            get
            {
                return _UkonceneKto;
            }
            set
            {
                OnUkonceneKtoChanging(value);
                ReportPropertyChanging("UkonceneKto");
                _UkonceneKto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UkonceneKto");
                OnUkonceneKtoChanged();
            }
        }
        private global::System.String _UkonceneKto;
        partial void OnUkonceneKtoChanging(global::System.String value);
        partial void OnUkonceneKtoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpedovaneKedy
        {
            get
            {
                return _ExpedovaneKedy;
            }
            set
            {
                OnExpedovaneKedyChanging(value);
                ReportPropertyChanging("ExpedovaneKedy");
                _ExpedovaneKedy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpedovaneKedy");
                OnExpedovaneKedyChanged();
            }
        }
        private global::System.String _ExpedovaneKedy;
        partial void OnExpedovaneKedyChanging(global::System.String value);
        partial void OnExpedovaneKedyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpedovaneKto
        {
            get
            {
                return _ExpedovaneKto;
            }
            set
            {
                OnExpedovaneKtoChanging(value);
                ReportPropertyChanging("ExpedovaneKto");
                _ExpedovaneKto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpedovaneKto");
                OnExpedovaneKtoChanged();
            }
        }
        private global::System.String _ExpedovaneKto;
        partial void OnExpedovaneKtoChanging(global::System.String value);
        partial void OnExpedovaneKtoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Oznacenie
        {
            get
            {
                return _Oznacenie;
            }
            set
            {
                OnOznacenieChanging(value);
                ReportPropertyChanging("Oznacenie");
                _Oznacenie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Oznacenie");
                OnOznacenieChanged();
            }
        }
        private global::System.String _Oznacenie;
        partial void OnOznacenieChanging(global::System.String value);
        partial void OnOznacenieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChybaKedy
        {
            get
            {
                return _ChybaKedy;
            }
            set
            {
                OnChybaKedyChanging(value);
                ReportPropertyChanging("ChybaKedy");
                _ChybaKedy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ChybaKedy");
                OnChybaKedyChanged();
            }
        }
        private global::System.String _ChybaKedy;
        partial void OnChybaKedyChanging(global::System.String value);
        partial void OnChybaKedyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChybaKto
        {
            get
            {
                return _ChybaKto;
            }
            set
            {
                OnChybaKtoChanging(value);
                ReportPropertyChanging("ChybaKto");
                _ChybaKto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ChybaKto");
                OnChybaKtoChanged();
            }
        }
        private global::System.String _ChybaKto;
        partial void OnChybaKtoChanging(global::System.String value);
        partial void OnChybaKtoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KalibraciaResult
        {
            get
            {
                return _KalibraciaResult;
            }
            set
            {
                OnKalibraciaResultChanging(value);
                ReportPropertyChanging("KalibraciaResult");
                _KalibraciaResult = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KalibraciaResult");
                OnKalibraciaResultChanged();
            }
        }
        private global::System.String _KalibraciaResult;
        partial void OnKalibraciaResultChanging(global::System.String value);
        partial void OnKalibraciaResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OdchylkaInterna
        {
            get
            {
                return _OdchylkaInterna;
            }
            set
            {
                OnOdchylkaInternaChanging(value);
                ReportPropertyChanging("OdchylkaInterna");
                _OdchylkaInterna = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OdchylkaInterna");
                OnOdchylkaInternaChanged();
            }
        }
        private global::System.String _OdchylkaInterna;
        partial void OnOdchylkaInternaChanging(global::System.String value);
        partial void OnOdchylkaInternaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OdchylkaZakaznik
        {
            get
            {
                return _OdchylkaZakaznik;
            }
            set
            {
                OnOdchylkaZakaznikChanging(value);
                ReportPropertyChanging("OdchylkaZakaznik");
                _OdchylkaZakaznik = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OdchylkaZakaznik");
                OnOdchylkaZakaznikChanged();
            }
        }
        private global::System.String _OdchylkaZakaznik;
        partial void OnOdchylkaZakaznikChanging(global::System.String value);
        partial void OnOdchylkaZakaznikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KontrolaSnimacaUsekomKvality
        {
            get
            {
                return _KontrolaSnimacaUsekomKvality;
            }
            set
            {
                OnKontrolaSnimacaUsekomKvalityChanging(value);
                ReportPropertyChanging("KontrolaSnimacaUsekomKvality");
                _KontrolaSnimacaUsekomKvality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KontrolaSnimacaUsekomKvality");
                OnKontrolaSnimacaUsekomKvalityChanged();
            }
        }
        private global::System.String _KontrolaSnimacaUsekomKvality;
        partial void OnKontrolaSnimacaUsekomKvalityChanging(global::System.String value);
        partial void OnKontrolaSnimacaUsekomKvalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DatumVytvoreniasnimaca
        {
            get
            {
                return _DatumVytvoreniasnimaca;
            }
            set
            {
                OnDatumVytvoreniasnimacaChanging(value);
                ReportPropertyChanging("DatumVytvoreniasnimaca");
                _DatumVytvoreniasnimaca = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DatumVytvoreniasnimaca");
                OnDatumVytvoreniasnimacaChanged();
            }
        }
        private global::System.String _DatumVytvoreniasnimaca;
        partial void OnDatumVytvoreniasnimacaChanging(global::System.String value);
        partial void OnDatumVytvoreniasnimacaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ontrolaSnimacaUsekomKvalityKto
        {
            get
            {
                return _ontrolaSnimacaUsekomKvalityKto;
            }
            set
            {
                OnontrolaSnimacaUsekomKvalityKtoChanging(value);
                ReportPropertyChanging("ontrolaSnimacaUsekomKvalityKto");
                _ontrolaSnimacaUsekomKvalityKto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ontrolaSnimacaUsekomKvalityKto");
                OnontrolaSnimacaUsekomKvalityKtoChanged();
            }
        }
        private global::System.String _ontrolaSnimacaUsekomKvalityKto;
        partial void OnontrolaSnimacaUsekomKvalityKtoChanging(global::System.String value);
        partial void OnontrolaSnimacaUsekomKvalityKtoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ontrolaSnimacaUsekomKvalityKedy
        {
            get
            {
                return _ontrolaSnimacaUsekomKvalityKedy;
            }
            set
            {
                OnontrolaSnimacaUsekomKvalityKedyChanging(value);
                ReportPropertyChanging("ontrolaSnimacaUsekomKvalityKedy");
                _ontrolaSnimacaUsekomKvalityKedy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ontrolaSnimacaUsekomKvalityKedy");
                OnontrolaSnimacaUsekomKvalityKedyChanged();
            }
        }
        private global::System.String _ontrolaSnimacaUsekomKvalityKedy;
        partial void OnontrolaSnimacaUsekomKvalityKedyChanging(global::System.String value);
        partial void OnontrolaSnimacaUsekomKvalityKedyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaDBcsharpModel", Name="tblObjednavkyStav")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblObjednavkyStav : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblObjednavkyStav object.
        /// </summary>
        /// <param name="idObjednavkyStav">Initial value of the IdObjednavkyStav property.</param>
        public static tblObjednavkyStav CreatetblObjednavkyStav(global::System.Int32 idObjednavkyStav)
        {
            tblObjednavkyStav tblObjednavkyStav = new tblObjednavkyStav();
            tblObjednavkyStav.IdObjednavkyStav = idObjednavkyStav;
            return tblObjednavkyStav;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdObjednavkyStav
        {
            get
            {
                return _IdObjednavkyStav;
            }
            set
            {
                if (_IdObjednavkyStav != value)
                {
                    OnIdObjednavkyStavChanging(value);
                    ReportPropertyChanging("IdObjednavkyStav");
                    _IdObjednavkyStav = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdObjednavkyStav");
                    OnIdObjednavkyStavChanged();
                }
            }
        }
        private global::System.Int32 _IdObjednavkyStav;
        partial void OnIdObjednavkyStavChanging(global::System.Int32 value);
        partial void OnIdObjednavkyStavChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StavObjednavky
        {
            get
            {
                return _StavObjednavky;
            }
            set
            {
                OnStavObjednavkyChanging(value);
                ReportPropertyChanging("StavObjednavky");
                _StavObjednavky = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StavObjednavky");
                OnStavObjednavkyChanged();
            }
        }
        private global::System.String _StavObjednavky;
        partial void OnStavObjednavkyChanging(global::System.String value);
        partial void OnStavObjednavkyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaDBcsharpModel", Name="tblSnimaceZoznam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSnimaceZoznam : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSnimaceZoznam object.
        /// </summary>
        /// <param name="idSnimaceZoznam">Initial value of the IdSnimaceZoznam property.</param>
        public static tblSnimaceZoznam CreatetblSnimaceZoznam(global::System.Int32 idSnimaceZoznam)
        {
            tblSnimaceZoznam tblSnimaceZoznam = new tblSnimaceZoznam();
            tblSnimaceZoznam.IdSnimaceZoznam = idSnimaceZoznam;
            return tblSnimaceZoznam;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSnimaceZoznam
        {
            get
            {
                return _IdSnimaceZoznam;
            }
            set
            {
                if (_IdSnimaceZoznam != value)
                {
                    OnIdSnimaceZoznamChanging(value);
                    ReportPropertyChanging("IdSnimaceZoznam");
                    _IdSnimaceZoznam = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdSnimaceZoznam");
                    OnIdSnimaceZoznamChanged();
                }
            }
        }
        private global::System.Int32 _IdSnimaceZoznam;
        partial void OnIdSnimaceZoznamChanging(global::System.Int32 value);
        partial void OnIdSnimaceZoznamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypSnimaca
        {
            get
            {
                return _TypSnimaca;
            }
            set
            {
                OnTypSnimacaChanging(value);
                ReportPropertyChanging("TypSnimaca");
                _TypSnimaca = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TypSnimaca");
                OnTypSnimacaChanged();
            }
        }
        private global::System.String _TypSnimaca;
        partial void OnTypSnimacaChanging(global::System.String value);
        partial void OnTypSnimacaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Skupina
        {
            get
            {
                return _Skupina;
            }
            set
            {
                OnSkupinaChanging(value);
                ReportPropertyChanging("Skupina");
                _Skupina = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Skupina");
                OnSkupinaChanged();
            }
        }
        private global::System.String _Skupina;
        partial void OnSkupinaChanging(global::System.String value);
        partial void OnSkupinaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaDBcsharpModel", Name="tblUzivatelia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUzivatelia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUzivatelia object.
        /// </summary>
        /// <param name="idUzivatela">Initial value of the IdUzivatela property.</param>
        public static tblUzivatelia CreatetblUzivatelia(global::System.Int32 idUzivatela)
        {
            tblUzivatelia tblUzivatelia = new tblUzivatelia();
            tblUzivatelia.IdUzivatela = idUzivatela;
            return tblUzivatelia;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUzivatela
        {
            get
            {
                return _IdUzivatela;
            }
            set
            {
                if (_IdUzivatela != value)
                {
                    OnIdUzivatelaChanging(value);
                    ReportPropertyChanging("IdUzivatela");
                    _IdUzivatela = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUzivatela");
                    OnIdUzivatelaChanged();
                }
            }
        }
        private global::System.Int32 _IdUzivatela;
        partial void OnIdUzivatelaChanging(global::System.Int32 value);
        partial void OnIdUzivatelaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Skupina
        {
            get
            {
                return _Skupina;
            }
            set
            {
                OnSkupinaChanging(value);
                ReportPropertyChanging("Skupina");
                _Skupina = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Skupina");
                OnSkupinaChanged();
            }
        }
        private global::System.String _Skupina;
        partial void OnSkupinaChanging(global::System.String value);
        partial void OnSkupinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Meno
        {
            get
            {
                return _Meno;
            }
            set
            {
                OnMenoChanging(value);
                ReportPropertyChanging("Meno");
                _Meno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Meno");
                OnMenoChanged();
            }
        }
        private global::System.String _Meno;
        partial void OnMenoChanging(global::System.String value);
        partial void OnMenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Heslo
        {
            get
            {
                return _Heslo;
            }
            set
            {
                OnHesloChanging(value);
                ReportPropertyChanging("Heslo");
                _Heslo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Heslo");
                OnHesloChanged();
            }
        }
        private global::System.String _Heslo;
        partial void OnHesloChanging(global::System.String value);
        partial void OnHesloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Opravnenie
        {
            get
            {
                return _Opravnenie;
            }
            set
            {
                OnOpravnenieChanging(value);
                ReportPropertyChanging("Opravnenie");
                _Opravnenie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Opravnenie");
                OnOpravnenieChanged();
            }
        }
        private global::System.String _Opravnenie;
        partial void OnOpravnenieChanging(global::System.String value);
        partial void OnOpravnenieChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaDBcsharpModel", Name="tblZakazky")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblZakazky : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblZakazky object.
        /// </summary>
        /// <param name="idZakazka">Initial value of the IdZakazka property.</param>
        public static tblZakazky CreatetblZakazky(global::System.Int32 idZakazka)
        {
            tblZakazky tblZakazky = new tblZakazky();
            tblZakazky.IdZakazka = idZakazka;
            return tblZakazky;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdZakazka
        {
            get
            {
                return _IdZakazka;
            }
            set
            {
                if (_IdZakazka != value)
                {
                    OnIdZakazkaChanging(value);
                    ReportPropertyChanging("IdZakazka");
                    _IdZakazka = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdZakazka");
                    OnIdZakazkaChanged();
                }
            }
        }
        private global::System.Int32 _IdZakazka;
        partial void OnIdZakazkaChanging(global::System.Int32 value);
        partial void OnIdZakazkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CisloZakazky
        {
            get
            {
                return _CisloZakazky;
            }
            set
            {
                OnCisloZakazkyChanging(value);
                ReportPropertyChanging("CisloZakazky");
                _CisloZakazky = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CisloZakazky");
                OnCisloZakazkyChanged();
            }
        }
        private Nullable<global::System.Int32> _CisloZakazky;
        partial void OnCisloZakazkyChanging(Nullable<global::System.Int32> value);
        partial void OnCisloZakazkyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZakazkaVytvoril
        {
            get
            {
                return _ZakazkaVytvoril;
            }
            set
            {
                OnZakazkaVytvorilChanging(value);
                ReportPropertyChanging("ZakazkaVytvoril");
                _ZakazkaVytvoril = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZakazkaVytvoril");
                OnZakazkaVytvorilChanged();
            }
        }
        private global::System.String _ZakazkaVytvoril;
        partial void OnZakazkaVytvorilChanging(global::System.String value);
        partial void OnZakazkaVytvorilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZakazkaVytvorilKedy
        {
            get
            {
                return _ZakazkaVytvorilKedy;
            }
            set
            {
                OnZakazkaVytvorilKedyChanging(value);
                ReportPropertyChanging("ZakazkaVytvorilKedy");
                _ZakazkaVytvorilKedy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZakazkaVytvorilKedy");
                OnZakazkaVytvorilKedyChanged();
            }
        }
        private global::System.String _ZakazkaVytvorilKedy;
        partial void OnZakazkaVytvorilKedyChanging(global::System.String value);
        partial void OnZakazkaVytvorilKedyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZakazkaStav
        {
            get
            {
                return _ZakazkaStav;
            }
            set
            {
                OnZakazkaStavChanging(value);
                ReportPropertyChanging("ZakazkaStav");
                _ZakazkaStav = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZakazkaStav");
                OnZakazkaStavChanged();
            }
        }
        private global::System.String _ZakazkaStav;
        partial void OnZakazkaStavChanging(global::System.String value);
        partial void OnZakazkaStavChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zakaznik
        {
            get
            {
                return _Zakaznik;
            }
            set
            {
                OnZakaznikChanging(value);
                ReportPropertyChanging("Zakaznik");
                _Zakaznik = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zakaznik");
                OnZakaznikChanged();
            }
        }
        private global::System.String _Zakaznik;
        partial void OnZakaznikChanging(global::System.String value);
        partial void OnZakaznikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZakazkaPoznamky
        {
            get
            {
                return _ZakazkaPoznamky;
            }
            set
            {
                OnZakazkaPoznamkyChanging(value);
                ReportPropertyChanging("ZakazkaPoznamky");
                _ZakazkaPoznamky = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZakazkaPoznamky");
                OnZakazkaPoznamkyChanged();
            }
        }
        private global::System.String _ZakazkaPoznamky;
        partial void OnZakazkaPoznamkyChanging(global::System.String value);
        partial void OnZakazkaPoznamkyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vykladka
        {
            get
            {
                return _Vykladka;
            }
            set
            {
                OnVykladkaChanging(value);
                ReportPropertyChanging("Vykladka");
                _Vykladka = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vykladka");
                OnVykladkaChanged();
            }
        }
        private global::System.String _Vykladka;
        partial void OnVykladkaChanging(global::System.String value);
        partial void OnVykladkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DatumUkoncenia
        {
            get
            {
                return _DatumUkoncenia;
            }
            set
            {
                OnDatumUkonceniaChanging(value);
                ReportPropertyChanging("DatumUkoncenia");
                _DatumUkoncenia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatumUkoncenia");
                OnDatumUkonceniaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DatumUkoncenia;
        partial void OnDatumUkonceniaChanging(Nullable<global::System.DateTime> value);
        partial void OnDatumUkonceniaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaDBcsharpModel", Name="tblZakazkyStav")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblZakazkyStav : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblZakazkyStav object.
        /// </summary>
        /// <param name="idStav">Initial value of the IdStav property.</param>
        public static tblZakazkyStav CreatetblZakazkyStav(global::System.Int32 idStav)
        {
            tblZakazkyStav tblZakazkyStav = new tblZakazkyStav();
            tblZakazkyStav.IdStav = idStav;
            return tblZakazkyStav;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdStav
        {
            get
            {
                return _IdStav;
            }
            set
            {
                if (_IdStav != value)
                {
                    OnIdStavChanging(value);
                    ReportPropertyChanging("IdStav");
                    _IdStav = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdStav");
                    OnIdStavChanged();
                }
            }
        }
        private global::System.Int32 _IdStav;
        partial void OnIdStavChanging(global::System.Int32 value);
        partial void OnIdStavChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StavZakazky
        {
            get
            {
                return _StavZakazky;
            }
            set
            {
                OnStavZakazkyChanging(value);
                ReportPropertyChanging("StavZakazky");
                _StavZakazky = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StavZakazky");
                OnStavZakazkyChanged();
            }
        }
        private global::System.String _StavZakazky;
        partial void OnStavZakazkyChanging(global::System.String value);
        partial void OnStavZakazkyChanged();

        #endregion
    
    }

    #endregion
    
}
